;(function(window,$,mw,Wikia){'use strict';var i18n={en:{refreshText:'AJAX',loadStatusAlt:'Refreshing page',refreshHover:'Enable page auto-refresh'},be:{loadStatusAlt:'Абнаўленне старонак',refreshHover:'Ўключыць аўтаматычнае абнаўленне загружанай старонкі'},bg:{refreshHover:'Обнови тази страница автоматично'},bs:{refreshHover:'Uključi auto-ažuriranje za ovu stranicu'},ca:{refreshHover:'Actualiza aquesta pàgina automàticament'},cs:{loadStatusAlt:'Obnovování stránky',refreshHover:'Automaticky obnovit tuto stránku'},da:{refreshHover:'Opdater siden automatisk'},de:{loadStatusAlt:'Aktualisiere Seite',refreshHover:'Aktiviere die automatische Aktualisierung der Seite'},el:{refreshHover:'Ανανέωση αυτής σελίδας'},eo:{refreshHover:'Ĝisdatigu ĉi tiun paĝon aŭtomate'},es:{loadStatusAlt:'Actualizando página',refreshHover:'Actualizar esta página automáticamente',},eu:{
refreshHover:'Orrialde hau automatikoki eguneratu'},fr:{refreshHover:'Actualiser automatiquement la page'},fy:{loadStatusAlt:'Side ferfarskje',refreshHover:'Ferfarskje dizze side Automatysk'},ga:{refreshHover:'Athnuaigh an leathanach seo go huathoibríoch'},gl:{refreshHover:'Actualizar a páxina automaticamente'},hr:{refreshHover:'Uključi auto-ažuriranje za ovu stranicu'},it:{refreshHover:'Aggiorna automaticamente la pagina'},ja:{loadStatusAlt:'自動更新',refreshHover:'このページを自動的に更新します'},ko:{loadStatusAlt:'문서 새로고침',refreshHover:'문서 자동 새로고침 활성화',},la:{refreshHover:'Hanc paginam automatice renovare'},mo:{refreshHover:'Актуализаци ачастэ паӂинэ ын мод аутомат'},nl:{loadStatusAlt:'Pagina verversen',refreshHover:'Ververs deze pagina automatisch'},'nl-informal':{loadStatusAlt:'Pagina verversen',refreshHover:'Ververs deze pagina automatisch'},no:{refreshHover:'Oppdater siden automatisk'},oc:
{refreshHover:'Actualizatz aquesta pagina automaticament'},pl:{refreshHover:'Aktywuj automatyczyne odświeżanie strony'},pt:{refreshHover:'Actualizar a página automaticamente'},'pt-br':{loadStatusAlt:'Atualizando página',refreshHover:'Ativa a atualização automática da página',},ro:{refreshHover:'Actualizaţi această pagină în mod automat'},ru:{loadStatusAlt:'Обновление страниц',refreshHover:'Включить автоматическое обновление загружаемой страницы'},sr:{refreshHover:'Укључи ауто-ажурирање за ову страницу'},sv:{refreshHover:'Uppdatera sidan automatiskt'},tr:{refreshHover:'Otomatik yenilenen sayfa yüklemelerine izin ver'},uk:{loadStatusAlt:'Оновлення сторінок',refreshHover:'Увімкнути автоматичне оновлення завантаженої сторінки'},val:{refreshHover:'Actualisar esta pàgina automàticament'},zh:{loadStatusAlt:
'正在刷新页面',refreshHover:'自动刷新页面'},'zh-hant':{loadStatusAlt:'正在重整頁面',refreshHover:'自動重新載入頁面更動'},},config=mw.config.get(['stylepath','wgAction','wgCanonicalSpecialPageName','wgPageName','wgUserLanguage']),ajaxIndicator=window.ajaxIndicator||config.stylepath+'/common/images/ajax.gif',ajaxTimer,ajRefresh=window.ajaxRefresh||60000,ajPages=window.ajaxPages||[],ajSpecialPages=window.ajaxSpecialPages||['Recentchanges'],disallowActions=['delete','edit','protect','revisiondelete'],href=location.href.replace(/#[\S]*/,'');function getMessage(msgKey,globalKey){if(globalKey&&typeof window[globalKey]==='string'){return window[globalKey];}var lang=config.wgUserLanguage,splitLang=lang.split('-')[0];if(i18n[lang]&&i18n[lang][msgKey]){return i18n[lang][msgKey];}if(i18n[splitLang]&&i18n[splitLang][msgKey]){return i18n[splitLang][msgKey];}return i18n.en[msgKey];}function storage(setTo){if(localStorage.getItem('AjaxRC-refresh')===null){localStorage.
setItem('AjaxRC-refresh',true);}if(setTo===true||setTo===false){localStorage.setItem('AjaxRC-refresh',setTo);}return JSON.parse(localStorage.getItem('AjaxRC-refresh'));}function getAppTo(){var $ret;$ret=$('.firstHeading');if($ret.length){return $ret;}$ret=$('.WikiaPage .page-header__main');if($ret.length){return $ret;}return false;}function loadPageData(){var $temp=$('<div>');$temp.load(href+' #mw-content-text',function(){var $newContent=$temp.children('#mw-content-text');if($newContent.length){$('#mw-content-text').replaceWith($newContent);mw.util.$content=$newContent;}ajaxTimer=setTimeout(loadPageData,ajRefresh);});$temp.remove();}function toggleAjaxReload(){if($('#ajaxToggle').prop('checked')){storage(true);loadPageData();}else{storage(false);clearTimeout(ajaxTimer);}}function preloadAJAXRL(){var $appTo=getAppTo(),$checkbox=$('<span>').attr('id','ajaxRefresh').css({'font-size':'xx-small','line-height':'100%','margin-left':'5px'}).append($('<label>').attr({id:'ajaxToggleText','for':
'ajaxToggle',title:getMessage('refreshHover','AjaxRCRefreshHoverText')}).text(getMessage('refreshText','AjaxRCRefreshText')+':').css({'border-bottom':'1px dotted',cursor:'help'}),$('<input>').attr({id:'ajaxToggle',type:'checkbox'}).css('margin-bottom',0),$('<span>').attr('id','ajaxLoadProgress').css('display','none').append($('<img>').attr({alt:getMessage('loadStatusAlt',false),src:ajaxIndicator}).css({'vertical-align':'baseline',float:'none',border:0}))),$throbber;if($appTo===false){$('#WikiaArticle').prepend($checkbox);}else{$appTo.append($checkbox);}$throbber=$checkbox.find('#ajaxLoadProgress');$(document).ajaxSend(function(_,_2,settings){if(href===settings.url){$throbber.show();}}).ajaxComplete(function(_,_2,settings){var $collapsibleElements=$('#mw-content-text').find('.mw-collapsible'),ajCallAgain=window.ajaxCallAgain||[],i;if(href===settings.url){$throbber.hide();if($collapsibleElements.length){$collapsibleElements.makeCollapsible();}if(config.wgCanonicalSpecialPageName===
'Recentchanges'){mw.special.recentchanges.init();if($('.mw-recentchanges-table').find('.WikiaDropdown').length){Wikia.RecentChanges.init();}}if(config.wgCanonicalSpecialPageName==='WikiActivity'){window.WikiActivity.init();}for(i=0;i<ajCallAgain.length;i++){if($.isFunction(ajCallAgain[i])){ajCallAgain[i]();}else{console.log('AjaxRC Error: Could not call non-function after reload.');}}}});$('#ajaxToggle').attr('checked',storage()).click(toggleAjaxReload);if(storage()){loadPageData();}}$(function(){if((ajPages.indexOf(config.wgPageName)>-1||ajSpecialPages.indexOf(config.wgCanonicalSpecialPageName)>-1)&&!$('#ajaxToggle').length&&disallowActions.indexOf(config.wgAction)===-1){if($('#mw-content-text .mw-collapsible').exists()){mw.loader.using('jquery.makeCollapsible',preloadAJAXRL);}else{preloadAJAXRL();}}});}(this,jQuery,mediaWiki,Wikia));;(function(window,$,mw){'use strict';var translations={ar:'عد إلى أعلى',af:'Terug na bo',be:'Наверх',bg:
'Върнете се в началото',bs:'Vratite se na vrh',ca:'Torna a dalt',de:'Zurück nach oben',el:'Επιστροφή στην κορυφή',en:'Back to top',eo:'Revenu supren',es:'Volver arriba',eu:'Gora itzuli',fr:'Retourner en haut',gl:'Volver arriba',hr:'Vratite se na vrh',it:'Torna in cima',la:'Ad supra tornare',ja:'ページ先頭へ戻る',ko:'맨 위로',mk:'Вратете се во почетокот',mo:'Ынтоарчере ла ынчепут',ms:'Kembali ke atas',nl:'Terug naar boven',oc:'Tornatz amunt',pl:'Wróć do góry',pt:'Voltar ao topo','pt-br':'Voltar ao topo',ro:'Întoarcere la început',ru:'Наверх',sco:'Back tae tap',sl:'Vrnete se na vrh',sr:'Вратите се на врх',tl:'Ibalik sa Itaas',uk:'Нагору',val:'Tornar amunt',vi:'Lên đầu trang',zh:'回到页首','zh-hans':'回到页首','zh-hant':'回到頁首'},buttonStart=typeof window.BackToTopStart==='number'?window.BackToTopStart:800,scrollSpeed=typeof window.BackToTopSpeed===
'number'?window.BackToTopSpeed:600,fadeSwitch=typeof window.BackToTopFade==='number'?window.BackToTopFade:600,theText=(typeof window.BackToTopText==='string'&&window.BackToTopText)||translations[mw.config.get('wgContentLanguage')]||translations.en;if(window.BackToTopLoaded){return}window.BackToTopLoaded=!0;$(addBackToTop);function hideFade(){$("#backtotop").hide();$(window).scroll(function(){if($(this).scrollTop()>buttonStart){switch(fadeSwitch){case 0:$('#backtotop').show();break;default:$('#backtotop').fadeIn();break;}}else{switch(fadeSwitch){case 0:$('#backtotop').hide();break;default:$('#backtotop').fadeOut();break;}}});}$('#backtotop').click(function(){$('body,html').animate({scrollTop:0},scrollSpeed);return false;});function addBackToTop(){$('<li />',{id:'backtotop',style:'float: right; margin-top: -1px; border-right: none'}).append($('<button />',{type:'button',style:'height: 20px;',text:theText})).appendTo('#WikiaBarWrapper .toolbar > .tools');hideFade();}}(this,jQuery,
mediaWiki));;window.dev=window.dev||{};dev.ReferencePopups=dev.ReferencePopups||{};dev.ReferencePopups.unload=dev.ReferencePopups.unload||function(){"use strict";delete this.Popup;delete this.configure;if(this.unloadCore){this.unloadCore();}};(function(module,lang){"use strict";var i18n={en:{coreConfigureText:'Configure Reference Popups',coreConfigureHover:'Change settings for Reference Popups'},ar:{coreConfigureText:'اضبط تلميحات المراجع',coreConfigureHover:'اضبط إعدادات تلميح المراجع'},be:{coreConfigureText:'Налада усплываючых падказак',coreConfigureHover:'Змяніць налады усплываючых падказак'},ca:{coreConfigureText:'Configura referències emergents',coreConfigureHover:'Canviar la configuració de referències emergents'},es:{coreConfigureText:'Configurar popups de referencias',coreConfigureHover:'Modificar la configuración de los popups de referencias'},fr:{coreConfigureText:
'Configurer Popups de Référence',coreConfigureHover:'Modifier les préférences pour les Popups de Référence'},it:{coreConfigureText:'Configura le note a popup',coreConfigureHover:'Cambia le impostazioni per le note a popup'},ja:{coreConfigureText:'注釈ふきだしの設定',coreConfigureHover:'注釈ふきだしの設定を変更する'},ko:{coreConfigureText:'주석 말풍선 설정',coreConfigureHover:'주석 말풍선 설정하기'},nl:{coreConfigureText:'Configureer Referentie Popups',coreConfigureHover:'Wijzig de instellingen voor Referentie Popups'},pl:{coreConfigureText:'Skonfiguruj wyskakujące przypisy',coreConfigureHover:'Zmień ustawienia dla wyskakujących przypisów'},ru:{coreConfigureText:'Настройка всплывающих подсказок',coreConfigureHover:'Изменить настройки всплывающих подсказок'},'pt-br':{coreConfigureText:'Configurar Popups de Referência',coreConfigureHover:
'Mudar configurações para Popups de Referência'},uk:{coreConfigureText:'Налаштування спливаючих підказок',coreConfigureHover:'Змінити налаштування спливаючих підказок'},vi:{coreConfigureText:'Thiết Đặt Popup Tham Khảo',coreConfigureHover:'Thay đổi thiết đặt cho Popup Tham Khảo'},};var msg=module.messages=module.messages||{};for(var m in i18n.en){msg[m]=msg[m]||(i18n[lang]&&i18n[lang][m])||i18n.en[m];}})(dev.ReferencePopups,mediaWiki.config.get('wgUserLanguage'));(function(window,$,mw){"use strict";var module=window.dev.ReferencePopups;if(module.Popup){return $.noop;}var mwReady=$.Deferred(),mwDeps=['jquery.ui.position','jquery.effects.fold','jquery.ui.core','jquery.ui.widget'];mw.loader.load(mwDeps,null,true);mw.loader.using(mwDeps,mwReady.resolve,mwReady.reject);var colors=window.dev.colors||$.ajax({url:mw.config.get('wgLoadScript'),data:{mode:'articles',only:'scripts',articles:
'u:dev:Colors/code.js'},dataType:'script',cache:!0});if(!module.cssLoaded){window.importArticle({type:'style',article:'u:dev:MediaWiki:ReferencePopups.css'});module.cssLoaded=!0;}var dfd=$.Deferred();module.Popup=dfd.promise();return function(callback){$.when(mwReady,colors).done(function(){dfd.resolve(module.Popup=callback(module,window,$,mw,window.dev.colors));}).fail(function(){delete module.Popup;dfd.reject();});};}(window,jQuery,mediaWiki))(function(module,window,$,mw,Colors){"use strict";$.curCSS=$.curCSS||$.css;(function(color,Colors,mw,$){function ifOk(val,alt){return(val&&val!=='transparent'&&val!=='rgba(0, 0, 0, 0)')?val:alt;}function tryParse(val,alt){try{return Colors.parse(val);}catch(e){if(window.console){window.console.warn('Colors Parse Error ('+val+'): ',e,e.stack);}return Colors.parse(alt);}}function toRgba(color,alpha){return'rgba('+color.red()+','+color.green()+','+color.blue()+','+alpha+')';}if(mw.config.get('skin')==='oasis'){color.page=Colors.parse(Colors.
wikia.page);color.pageBorder=Colors.parse(Colors.wikia.border);color.accent=Colors.parse(Colors.wikia.menu);color.popText=Colors.wikia.text;}else{var $content=$('#content');color.page=tryParse(ifOk($('#globalWrapper').css('backgroundColor'),$content.css('backgroundColor')),'white');color.pageBorder=tryParse(ifOk($content.css('borderLeftColor'),$content.css('borderRightColor')),'#AAA');color.accent=tryParse(ifOk($('#footer').css('borderTopColor'),$('body').css('backgroundColor')),'#fabd23');color.popText=tryParse($('#mw-content-text').css('color'),'black');}var mixCol;if(color.page.isBright()){color.back=color.page.mix(mixCol='black',95).mix('blue',97);}else{color.back=color.page.mix(mixCol='white',95);}color.popEdge=color.accent.mix(color.pageBorder,90);color.backA=toRgba(color.back,0.95);color.backB=toRgba(color.back.mix(mixCol,99),0.95);color.backC=toRgba(color.back.mix(mixCol,97),0.95);Colors.css(
'\
	.refpopups-box {\
		background-color: $back;\
		color: $popText;\
		border-color: $popEdge;\
		background: -webkit-linear-gradient(30deg, $backA, $backB 15%, $backB 25%, $backA 40%, $backA 50%, $backB 60%, $backB 70%, $backC 70%, $backC 90%, $backA 92%);\
		background: linear-gradient(60deg, $backA, $backB 15%, $backB 25%, $backA 40%, $backA 50%, $backB 60%, $backB 70%, $backC 70%, $backC 90%, $backA 92%);\
	}\
	.refpopups-chevron-in {\
		border-top-color: $back;\
		border-top-color: $backA;\
	}\
	.refpopups-flipped > .refpopups-chevron-in {\
		border-bottom-color: $back;\
		border-bottom-color: $backA;\
	}\
	.refpopups-chevron-out {\
		border-top-color: $popEdge;\
	}\
	.refpopups-flipped > .refpopups-chevron-out {\
		border-bottom-color: $popEdge;\
	}',color);})(module.colors=module.colors||{},Colors,mw,$);var widgetId=0;$.widget('Lunarity.referencePopup',{options:{activateBy:'hover',hoverDelay:200,content:'',disabled:!1,visible:!1,animation:'fold',animSpeed:300,context:null
,escapeCloses:!0,extraClass:'',contentBoxClass:'',stickyHover:!1,open:null,close:null},_create:function(){if(!this.document){this.document=$(this.element[0].ownerDocument);this.window=$(this.document[0].defaultView||this.document[0].parentWindow);this.eventNamespace='.'+this.widgetBaseClass+widgetId++;}this._timeouts={};this._$popup=$('<div class="refpopups-popup" id="'+this.eventNamespace.substr(1)+'">'+'<div class="refpopups-chevron-out"></div>'+'<div class="refpopups-chevron-in"></div>'+'<div class="refpopups-box">'+'</div></div>').addClass(this.options.extraClass).find('> .refpopups-box').addClass(this.options.contentBoxClass).end();this.options.context=$(this.document.find(this.options.context)[0]);if(!this.options.context.length){this.options.context=$(this.document[0].body);}this._setOption('activateBy',this.options.activateBy==='click'?'click':'hover');this._updateContent();if(!this.options.disabled){this.options.disabled=!0;this.enable();}if(this.options.visible){this.
options.visible=!1;this.show();}},_clearTimeout:function(name){if(this._timeouts[name]!==null){window.clearTimeout(this._timeouts[name]);this._timeouts[name]=null;}},_setTimeout:function(name,callback,delay){this._clearTimeout(name);var me=this;this._timeouts[name]=window.setTimeout(function(){me._timeouts[name]=null;callback.call(me);},delay||0);},_installEvents:function(){var self=this,map,ns=this.eventNamespace;this._$popup.off(ns);this.element.off(ns);this._clearTimeout('open');this._clearTimeout('close');if(this.options.disabled){return;}if(this.options.activateBy==='hover'){map={};map['mouseenter'+ns]=function(){self._clearTimeout('close');};map['mouseleave'+ns]=function(ev){self._setTimeout('close',function(){this.hide(ev);},self.options.hoverDelay);};this._$popup.on(map);map={};map['mouseenter'+ns]=function(ev){self._clearTimeout('close');self._setTimeout('open',function(){this.show(ev);},self.options.hoverDelay);};map['mouseleave'+ns]=function(ev){self._clearTimeout('open')
;if(!self.options.stickyHover){self._setTimeout('close',function(){this.hide(ev);},self.options.hoverDelay);}};this.element.on(map);}var lastTouch;map={};map['touchEnd'+ns]=function(ev){lastTouch=ev.originalEvent;};map['click'+ns]=function(ev){if((self.options.activateBy!=='click'&&(!lastTouch||lastTouch.defaultPrevented))||self.options.disabled){return;}lastTouch=null;if(!self.options.visible){ev.preventDefault();self.show(ev);}else{self.hide(ev);}};if(this.options.escapeCloses){var onKeyUp=function(ev){if(ev.which===$.ui.keyCode.ESCAPE){self.hide(ev);}};map['keyup'+ns]=onKeyUp;this._$popup.on('keyup'+ns,onKeyUp);}this.element.on(map);map=null;},triggerHover:function(event){if(this.options.activateBy==='hover'){this._setTimeout('open',function(){this.show(event);},this.options.hoverDelay);}},destroy:function(){this.hide();this._$popup.remove();this.element.off(this.eventNamespace);return $.Widget.prototype.destroy.call(this);},_updateContent:function(val){val=val||this.options.content
||'';if(!val.jquery&&!val.nodeType){this.options.content=val=$($(this.document[0].createElement('div')).html(val).contents().unwrap());}this._$popup.find('> .refpopups-box').empty().append(val);},_describeAria:function(yes){var k='aria-describedby',val=this.element.attr(k),s=val?val.split(/\s+/g):[],id=this._$popup[0].id,at=$.inArray(id,s);if(at!==-1){if(!yes){s.splice(at,1);}}else if(yes){s.push(id);}val=s.join(' ');this.element[val?'attr':'removeAttr'](k,val);},show:function(event){if(this.options.visible||this.options.disabled){return;}this.options.context.append(this._$popup.stop(true,true));this._positionPopup();this._describeAria(true);if(this.options.animation){this._$popup.hide().show(this.options.animation,this.options.animSpeed);}var triggered=0,self=this,ns=this.eventNamespace;this.window.on('scroll'+ns+' resize'+ns,function adaptCallback(){if(++triggered!==1){return;}self._positionPopup();window.setTimeout(function(){var t=triggered;triggered=0;if(t>1&&self.options.visible)
{adaptCallback();}},100);});if(this.options.activateBy==='click'){this.document.on('click'+ns,function(ev){if(!$(ev.target).closest(self._$popup.add(self.element)).length){self.hide();}});}this.options.visible=!0;this._trigger('open',event);},hide:function(event){if(!this.options.visible){return;}this.document.off(this.eventNamespace);this.window.off(this.eventNamespace);if(this.options.animation){var $clone=this._$popup.clone();this._$popup.after($clone);$clone.hide(this.options.animation,this.options.animSpeed,function(){$clone.remove();});}this._$popup.detach();this._describeAria(false);this.options.visible=!1;this._trigger('close',event);},toggle:function(yesno){yesno=(yesno!==void 0?yesno:!this.options.visible);this[yesno?'show':'hide']();},_setOption:function(key,val){switch(key){case'disabled':if(val&&this.options.visible){this.hide();}this.options.disabled=!!val;this._installEvents();return;case'visible':this[val?'show':'hide']();return;case'activateBy':if(({hover:1,click:
1})[val]===1){this.options.activateBy=val;this._installEvents();}return;case'content':this.options.content=val;this._updateContent();return;case'context':return;case'extraClass':this._$popup[0].className='refpopups-popup';this._$popup.addClass(val);break;case'extraBoxClass':this._$popup.find('> .refpopups-box').prop('className','refpopups-box').addClass(val);break;}return $.Widget.prototype._setOption.call(this,key,val);},_positionPopup:function(){var $popup=this._$popup.removeClass('refpopups-flipped'),$this=this.element,$chevOut=$popup.find('> .refpopups-chevron-out'),chevOutHeight=0;if($chevOut.is(':visible')){chevOutHeight=$chevOut.position().top+$chevOut.outerHeight()-$popup.outerHeight();}$popup.position({my:'bottom',at:'top',of:$this,collision:'fit none',offset:'0 -'+chevOutHeight});var spaceAtTop=$this.offset().top,spaceAtBottom=spaceAtTop+$this[0].offsetHeight,popupHeight=$popup[0].offsetHeight+chevOutHeight,scroll=this.window.scrollTop();spaceAtTop=spaceAtTop-scroll;
spaceAtBottom=(scroll+this.window.height())-spaceAtBottom;if(spaceAtTop<popupHeight&&spaceAtTop<spaceAtBottom){$popup.addClass('refpopups-flipped').position({my:'top',at:'bottom',of:$this,collision:'fit none',offset:'0 '+chevOutHeight});}if(!chevOutHeight){return;}var $chevIn=$popup.find('> .refpopups-chevron-in'),myLoc=$this.offset().left-$popup.offset().left+$this.outerWidth()/2;$chevOut.css('left',(myLoc-$chevOut.outerWidth()/2)+'px');$chevIn.css('left',(myLoc-$chevIn.outerWidth()/2)+'px');}});return $.Lunarity.referencePopup;});(function(window,$){"use strict";var module=window.dev.ReferencePopups;if(module.unloadCore){return $.noop;}module.unloadCore=$.noop;return function(callback){$.when(module.Popup).done(function(){callback(module,window,$,window.mediaWiki);}).fail(function(){delete module.unloadCore;});};}(window,jQuery))(function(module,window,$,mw){"use strict";var store={get:function(key){try{return JSON.parse(window.localStorage.getItem(key));}catch(e){return null;}},set:
function(key,data){try{window.localStorage.setItem(key,JSON.stringify(data));}catch(e){}}};var userConfig=(function(config,defaults){if(typeof(config)!=='object'||config===null){config={};}if(({hover:1,click:1})[config.react]!==1){config.react='hover';}config.hoverDelay=config.hoverDelay||defaults.hoverDelay||200;config.animate=(config.animate===void 0?defaults.animate===void 0||defaults.animate:!!config.animate);config.disabled=!!config.disabled&&!module.lockdown;config.stick=(config.stick===void 0?defaults.stick!==void 0&&defaults.stick:!!config.stick);return config;})(store.get('RefPopupsJS'),module.defaults||{});var armedPop=null,openPop=null;function cyclePopup(newTarget){if(openPop&&openPop.element.is(newTarget)){return;}if(armedPop){if(armedPop.element.is(newTarget)){return;}armedPop.destroy();}return(armedPop=constructPopup($(newTarget)));}function cleanupPopups(){if(openPop){openPop.destroy();}if(armedPop){armedPop.destroy();}openPop=armedPop=null;}$(function($){var lastTouch;
$('#mw-content-text').on({'touchEnd.RefPopups':function(ev){lastTouch=ev.originalEvent;},'click.RefPopups':function(ev){if(((!lastTouch||lastTouch.defaultPrevented)&&userConfig.react!=='click')||userConfig.disabled){return;}lastTouch=null;var pop=cyclePopup(this);if(pop){ev.preventDefault();pop.show(ev);}},'referencepopupopen.RefPopups':function(){if(!armedPop||!armedPop.element.is(this)){return;}var oldOpen=openPop;openPop=armedPop;armedPop=null;if(oldOpen){oldOpen.destroy();}},'referencepopupclose.RefPopups':function(){if(!openPop||!openPop.element.is(this)){return;}if(armedPop){openPop.destroy();}else{armedPop=openPop;}openPop=null;}},'.reference');$(window).on('pagehide.RefPopups',cleanupPopups);applyHoverEvents();});function applyHoverEvents(){var $article=$('#mw-content-text');$article.off('mouseenter.RefPopups');if(userConfig.disabled){return;}if(userConfig.react!=='hover'){if(openPop){openPop.option('activateBy','click');}if(armedPop){armedPop.option('activateBy','click');}
return;}$article.on('mouseenter.RefPopups','.reference',function(){var pop=cyclePopup(this);if(pop){pop.triggerHover();}});if(openPop){openPop.option('activateBy','hover');}if(armedPop){armedPop.option('activateBy','hover');}}if(!module.lockdown){$(function($){$('#articleCategories, #catlinks').first().after($('<a href="#configure-refpopups" class="refpopups-configure-page" />').html('['+module.messages.coreConfigureText+']').click(onClickConfigure).appendTo(this));});}module.unloadCore=function(){$('#mw-content-text').off('.RefPopups');$(window).off('.RefPopups');$('a[href="#configure-refpopups"]').remove();cleanupPopups();delete this.unloadCore;};$(window).trigger('dev-ReferencePopups-config',module.settings=$.extend({},userConfig));var configureIsPending=!1;function onClickConfigure(ev){ev.preventDefault();var closeFunc=function(){configureIsPending=!1;},interfaceFunc=function(confFunc){confFunc(userConfig,function(newSettings){store.set('RefPopupsJS',newSettings);
cleanupPopups();applyHoverEvents();$(window).trigger('dev-ReferencePopups-config',module.settings=$.extend({},newSettings));},closeFunc);};if(configureIsPending){return;}configureIsPending=!0;if(module.configure){$.when(module.configure).done(interfaceFunc).fail(closeFunc);return;}$.ajax({url:mw.config.get('wgLoadScript'),data:{mode:'articles',only:'scripts',articles:'w:dev:ReferencePopups/code.configure.js'},dataType:'script',cache:!0}).then(function(){$.when(module.configure).done(interfaceFunc).fail(closeFunc);}).fail(closeFunc);}function constructPopup($ref){var frag=$ref.find('a[href^="#cite_note"]').first();if(!frag.length){return null;}var $cite=$(frag.attr('href').replace(/\./g,'\\.'));if(!$cite.length){return null;}var $content=$('<div style="overflow:auto">'),$conf=$('<a href="#" class="refpopups-configure" />').prop('title',module.messages.coreConfigureHover).click(onClickConfigure);$content.append($cite.find('.reference-text').clone());return new module.Popup({content:
$conf.add($content),activateBy:userConfig.react,hoverDelay:userConfig.hoverDelay,animation:userConfig.animate&&'fold',stickyHover:userConfig.stick,contentBoxClass:'WikiaArticle'},$ref[0]);}});;;mw.loader.state({"wikia.fake.articles.744cb8295eb80e0b0dc78ccd48e87028":"ready"});

/* cache key: lotr:resourceloader:filter:minify-js:7:c6ee17c6542b8d92cfd9519dea0a9bd3 */
